- hosts: all
  become: yes
  tasks:
    - name: Update and install docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      docker_image:
        name: my-static-website
        source: local

    - name: Run Docker container
      docker_container:
        name: my_static_website
        image: my-static-website
        state: started
        ports:
          - "80:80"