- name: "AWS - Install Docker"
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3
        - python3-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Check if amazon-linux-extras is available
      stat:
        path: /usr/bin/amazon-linux-extras
      register: amazon_linux_extras_available

    - name: Install Docker using amazon-linux-extras
      command: amazon-linux-extras install -y docker
      when: amazon_linux_extras_available.stat.exists

    - name: Install Docker using yum for Amazon Linux
      yum:
        name: docker
        state: present
      when: not amazon_linux_extras_available.stat.exists

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ pip_packages }}"
      vars:
        pip_packages:
        - boto
        - boto3

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Load Docker image
      command: docker load -i /home/ec2-user/my-static-website.tar.gz

    - name: Run Docker container
      docker_container:
        name: my_static_website
        image: my-static-website
        state: started
        ports:
          - "80:80"